### ISSUE TITLE
Will there ever be a time when `./scripts/build.sh` will pass and `cargo build --release` will fail?

### ISSUE THREAD

**Issue by pard68** [substrate-developer-hub/substrate-collectables-workshop#97]
Wondering if both the build script and `cargo build` are needed _simply_ to verify that the module is correct. If the wasm build is successful than the llvm build should be successful too. The reason this matters is that the build script has close-enough-to-instant results that it doesn't delay the tutorial. However building with cargo takes considerably longer since it requires a good deal more packages, and thus ruins the flow of working through this tutorial. 

So long as the next step isn't using Polkadot, users should be able to just use the build script to verify that the module is compiling properly and than move onto the next section. `cargo` should only be needed if the next step is to actually run substrate.

**Comment by shawntabrizi** [comment]
@pard68 It is possible one passes while the other does not since `cargo build --release` depends on the STD libraries while `./scripts/build.sh` will not. But you are right, any issues at that level are kind of outside the scope of the tutorial, and really you should expect that if the Wasm builds, you are good to move on.

In general, bother `build.sh` and `cargo build --release` should be pretty fast once you get over the hump of building it the first time. You are right `cargo build --release` is only needed when you actually run your node (and in some cases you may not even need to rebuild it, you could just do a WASM upgrade).

I think your point is valid though, minutes can be saved by having users skip over the `cargo build --release` step, I could probably make that whole thing more clear in the tutorial by really going into detail about what each thing does, and why.

Do you have a suggestion where you would like to see a change made to make this more clear?

**Comment by JoshOrndorff** [comment]
This seems like a good place to me https://shawntabrizi.com/substrate-collectables-workshop/#/0/common-patterns-moving-forward

**Comment by hhicks13** [comment]
I have encountered cases where `./scripts/build.sh` will give me a rust compiler error and say that 'std' does not exist, but then I run `cargo build --release`, and it works fine. What does this mean?

**Comment by pard68** [comment]
Yea the spot @JoshOrndorff mentioned is where I was thinking of making this point.
